services:
  db:
    image: postgres:16-alpine
    container_name: evalc1_db
    environment:
      POSTGRES_DB: evalc1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_evalc1
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      DATABASE_URL: postgresql://postgres:postgres@db:5432/evalc1_db
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  postgres_data: